#!/usr/bin/env expect
#
# make sure we can debug a mesh
#

set path [lindex $argv 0]
set type [lindex $argv 1]
set ext [lindex $argv 2]

set timeout 30

spawn $path/../../build/bin/$type -g -o mesh-$type $path/mesh.$ext
expect "1 warning"
sleep 1
spawn $path/../../build/bin/lldb -- ./mesh-$type
expect "(lldb)"

send "b mesh.$ext:15\n"
expect {
    "at mesh.$ext:15" {
  }
  timeout {
    exit 1
  }
}

expect "(lldb)"

send "r\n"
expect {
    "int x = 9;" {
  }
  timeout {
    exit 1
  }
}

expect "(lldb)"

send "expr forall cells c in m {c.field = 10;}\n"
expect "(lldb)"

send "c\n"
expect {
    "10.0000" {
  }
  timeout {
    exit 1
  }
}

send "q\n"
#
